insert into user values (1,'Aishwarya','eedalaaishwarya@gmail.com')
insert into user values (2,'Jahnavi', 'kollijahnavi@gmail.com.com')
insert into user values (3,'Madhupriya', 'surasanimadhupriya@gmail.com')

insert into category values (1,'Travel')
insert into category values (2,'Auto Loan')
insert into category  values (3,'Groceries')
insert into category  values (4,'Healthcare')
insert into category  values (5,'Shopping')
insert into category  values (6,'Subscriptions')
insert into category  values (7,'Food')

insert into expense values (1,'Kedarnath','2024-01-03T17:00:00','12000','Noida','Travel')
insert into expense values (2,'Hyundai','2024-02-02T8:00:00','6000','Hyderabad','Auto Loan')
insert into expense values (3,'Thyroid Checkup','2024-03-12T12:00:00','3000','Vizag','Healthcare')
insert into expense values (4,'H&M','2024-04-30T14:00:00','5000','Bhopal','Shopping')

